Inter-Actief/amelie

- amelie/activities/templates/activity_list.html
- amelie/style/static/css/compiled.css
- amelie/style/static/less/page-specific/activity_list.less
It fixes the too wide activity labels on mobile view
#674 
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` …
> Fixed too wide labels on mobile view activities list -> master

- amelie/members/forms.py
It removes the eleven check from the employee member form, so (new) employees can become an Inter-Actief member.
Fixes Inter-Actief/amelie#546
no
no
No, my PR does not include translations
**Does your PR include CSS changes (and did you run the …
> Remove the eleven check from the employee form

- templates/frontpage.html
Reverts Inter-Actief/amelie#700
The widget actually does set two third party cookies on the discord.com domain, which is currently not allowed by our privacy policy. So we have to revert this for now.
We can look in to changing the policy, which would require us to add a cookie banner (I would vote against this), or try to use the discord API to build our own 'widget' with a similar view, that does not use cookies.
> Revert "Added widget for members, and in other place for board"

- CONTRIBUTING.md
A potential FileNotFoundError in a manage.py script, due to incorrect documentation.
During the generation of dummydata, the script looks at MEDIA_ROOT and removes an extra character. The tutorial specifies setting `MEDIA_ROOT = "/tmp/amelie_uploads/"`, however, this leads to trying to create `/tmp/amelie_uploads/ata/image/small/2023/04/12/1738-e7316016-c5dc-4dc9-99cd-a168cf11f0c3.png.jpg`.
The fix is to set `MEDIA_ROOT = "/tmp/amelie_uploads"`and NOT `MEDIA_ROOT = "/tmp/amelie_uploads/"`
This issue was found when @00maarten00 was trying to set up amelie on his laptop running Linux. I also verified (and fixed) the issue on MacOS.
**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References …
> Fix FileNotFoundError in www_generate_dummydata

- amelie/members/static/js/dogroup_tree.js
When people hover over the do-group family tree, all of the non-neighbouring nodes from the selected node disappear. However, this can cause quite some accidental flickering. In order to battle this the opacity of the non-neighbouring nodes is lowered, instead of completely removing them.
Additionally, I've added some documentation to the already existing code. 
Inter-Actief/amelie#780
no …
> Fade non-neighbouring nodes on node selection instead of disappearing them

- amelie/activities/templates/gallery_overview.html
Display the photo archive with the correct link in the gallery_overview.html page.
Fixes #725.
No
No
No, my PR does not include translations …
> Fix photo archive link and display

- amelie/activities/graphql.py
- amelie/files/graphql.py
- amelie/settings/generic.py
Add the public accessible data from the activities application to the GraphQL API
Fixes Inter-Actief/amelie#811
no
no …
> Add the activities module to graphql

- amelie/education/templates/complaint.html
- amelie/style/static/js/amelie.js
Fixes not all text in complaint comments not being removed when editing a comment
Fixes #726 
no
no …
> education: Fix comment editing not removing all text

- amelie/settings/generic.py
- amelie/tools/middleware.py
- templates/basis.html
This PR adds the book URL of WO4You, such that signed in members can view it.
This URL is in the local.py and also added in generic.py
Fixes/References Inter-Actief/amelie#807
no
no
yes, I have included the translations
**Does your PR include …
> Added WO4You URL

- amelie/activities/views.py
Previously the 'q' query string was not processed and the server would return all photo albums. Now a filter is applied as expected and only matching albums are returned. The search box on the website will only process a request once more than 2 characters are entered to prevent excessive traffic to and from the server. Since the query string is not automatically sent this restriction has not been applied on the query string.
`Fixes/References Inter-Actief/amelie#503`
**Does your PR change how we process personal data, impact our [privacy …
> 503: Process the q query string for photos

- amelie/files/models.py
Previously the albums were effectively randomly sorted. Now we look at the creation time in the database. This is not perfect if we want to order on when a photo was taken, but it is a lot better than before at no significant performance penalty or database change.
Previously the albums were effectively randomly sorted. Now we look at
the creation time in the database. This is not perfect if we want to
order on when a photo was taken, but it is a lot better than before at
no significant performance penalty or database change.
`Fixes Inter-Actief/amelie#719` …
> 719: Order photos by creation time.

- templates/basis.html
JS Was compressed on production, making the JS module not a JS module anymore and breaking the code.
Inter-Actief/amelie#851
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` …
> Made JS module not be compressed, as it would not be a module anymore

- amelie/style/static/css/compiled.css
- amelie/style/static/less/classes/helper-classes.less
- amelie/tools/forms.py
- amelie/tools/widgets.py
Changes date fields to use HTML input type date. This adds strict date formatting. Does NOT change DateTime fields since they use bootstrap to supply a datepicker.
Fixes/References #841 
no
no
**Does your …
> Add a date format hint

- amelie/graphql/decorators.py
- amelie/members/graphql.py
Adds field level authorization levels to GraphQL types using Python decorators.
Closes #846
> Add authorization levels to GraphQL

- amelie/members/views.py
In the statistics there are a few divisions where it would be possible to divide by zero. I've implemented a ternary operator to prevent divisions by zero.
Fixes/References Inter-Actief/amelie#892
no
no
**Does your PR include CSS changes (and did you run the …
> Prevent division by zero

- amelie/narrowcasting/views.py
Currently the log is spammed with spotify request errors. Also we are making 50k requests per day. To reduce the requests I've increased the spotify caching to 15 seconds. Also I have suppressed the errors.
Fixes/References Inter-Actief/amelie#903
no
no
**Does …
> Longer spotify caching and disabled logging for spotify rate limit exceeded

- amelie/narrowcasting/views.py
Catches the correct `ConnectionError` exception. There is both one defined within Python system and one by the `requests` library. Initially we would only catch the one from the Python system, which is most likely not the correct one.
Fixes Inter-Actief#926
no
no
**Does your PR include the proper translations (did you add translations for …
> 926 spotify network error narrowcasting

- amelie/personal_tab/static/js/personal_tab_pos.js
The cookie corner prices in the Dutch cookie corner were broken due to a faulty attempt at parsing Dutch prices. Dutch currencies are written as "0,00" instead of "0.00". This causes the `parseFloat` method from JavaScript to break and simply return 0. 
Fixes Inter-Actief#616
no
no
**Does your PR include the proper translations (did you add …
> Fix dutch cookie corner pricing

- amelie/narrowcasting/views.py
A second attempt at fixing the connection error message for the Spotify API.
Fixes Inter-Actief/amelie#926
no
no …
> Replace built-in ConnectionError by requests.exceptions.ConnectionError

- amelie/companies/views.py
Provide members of the KasCo access to the banners that are displayed on the website and television
No issue linked
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in …
> Give the KasCo access to the banners on the website and the television
