Inter-Actief/amelie

CONTRIBUTING.md

The CONTRIBUTING file missed some needed pacakges for Debian/Ubuntu. It also had a reference to amelie-private which has been updated.
<add issues references here>
no
no
**Does your PR include CSS changes …

docs: update required packages and link to amelie

---

amelie/__init__.py
amelie/activities/tasks.py
amelie/calendar/tasks.py
amelie/celeryapp.py
amelie/claudia/tasks.py
amelie/iamailer/tasks.py
amelie/members/tasks.py
amelie/settings/generic.py
requirements.txt
scripts/start_celery.sh

Updates requirements to Django-Auditlog 2.x, Celery 5.x, Flower 1.x and django-celery-results 2.x
Fixes #657 
yes/no
yes/no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script …

general: Update Celery and Auditlog

---

amelie/claudia/forms.py

Return email in clean_email
Fixes #693
no
no
no, my PR …

Fix claudia personal alias add form

---

amelie/narrowcasting/static/js/room_narrowcasting.js

update a check to let the narrowcasting page pause music again
#715 
on
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the …

Update room name

---

amelie/gmm/templates/gmm_overview.html

Updating link to "new" declaration policy document and mentioning when the document was last updated
Fixes Inter-Actief/amelie#735
no
no
**Does your PR include CSS changes (and did you run the …

Update declaration policy links and slightly change the text

---

amelie/members/templates/committees.html

Updated the committee booklet link to the current version
The committee booklet link on the committee page was linked to an outdated version
No issue
no
no
**Does your PR include CSS changes (and did you …

Updated committees.html

---

amelie/members/templates/birthday_mail.mail

Change width of picture used in the e-mail to get the desired 3:2 ratio
Fixes Inter-Actief/amelie#723
no
no …

Change height to get the desired 3:2 ratio

---

amelie/room_duty/templates/room_duty/table/print.html

Add a room duty task called 'Asito'
None
no
no
no, my …

Add room duty task

---

templates/basis.html

Since studystore does not sell books anymore, I have made a /about page with the current book list. This should only be merged when Q4 has been added.
#729 
no
no
**Does your PR include CSS changes (and …

Update book sale link to new /about page

---

amelie/gmm/templates/gmm_overview.html

Update the declaration policy on the GMM page
Fixes Inter-Actief/amelie#756
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate …

Declaration policy update

---

amelie/members/forms.py
amelie/members/templates/members/profile_changed.mail

Making the update of member preferences more visually appealing
Fixes Inter-Actief/amelie#752
no
no
\no, my PR does not include translations …

Implemented a cleaner preferences update

---

amelie/claudia/clau.py
amelie/claudia/plugins/gsuite_plugin.py

Fixes claudia bug: https://sentry.ia.utwente.nl/organizations/inter-actief/issues/17/?project=3
_none_
no
no …

claudia: Fix NoneType error in GoogleSuitePlugin

---

templates/basis.html

Update the books url to wo4you
None
no
no
no, my PR …

Update books url to wo4you

---

amelie/gmm/templates/gmm_overview.html

Add a link to the GMM decision list document
None
no
no …

Add link to decision list

---

amelie/blame/registrations.py

Fixes #785 
Fixes #785 
no
no
no, my PR does not …

Add Payment to blame

---

amelie/tools/management/commands/www_rechten.py

Create person in www_rechten for test account
Fixes #792
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` …

Create person in www_rechten for test account

---

templates/frontpage.html

Fixing the bug that makes the Dutch flag look weird on the main page.
Fixes #709.
No
No
No, my PR does not include translations
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to …

Fix Dutch flag bug

---

amelie/activities/models.py
amelie/activities/templates/includes/activity_enrollment.html
amelie/activities/views.py

Activity page now shows for which extra options you are enrolled.
Fixes/References Inter-Actief/amelie#837
no
no …

Added overview of extra options at activity page

---

amelie/activities/models.py

Fixes an edge-case where one gets an TypeError for unsupported operands between an int and None.
Fixes/References #864 
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` …

Prevent an int - None type error

---

amelie/activities/models.py

Forgot about another condition that could be None =
Fixes #864

Add additional check

---

amelie/personal_tab/helpers.py
amelie/personal_tab/test_helpers.py

Local equivalent of https://github.com/Inter-Actief/amelie/pull/885 so build pipeline works

Fixed kcal_equivalent crashing on some values

---

amelie/room_duty/models.py

Fixes an error causing the room duty log to not load
Fixes Inter-Actief/amelie#894
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to …

Fix positional and keyword error

---

amelie/urls.py

Fix the issue where people cannot switch between languages on the website.
Fixes Inter-Actief/amelie#897
no
no …

Add i18n urls

---

amelie/education/forms.py
amelie/education/templates/complaint_new.html

Added checkbox to complaints page, to confirm that the person has contacted a coordinator or teacher.
Fixes/References Inter-Actief/amelie#644
no
no
Does need translations, but Weblate is currently down. Will add them later.
**Does your PR …

644 checkbox complaints

---

amelie/style/static/css/christmas.css
amelie/style/static/css/compiled.css

Christmas hat might still cover some faces, but that depends on the position of the face. Moved the hat a bit up and to the right, to hopefully decrease the chance that it happens.
Fixed/References Inter-Actief/amelie#834
no
no
no, my PR does …

Adjusted position of christmas hat in profile menu.

---

amelie/activities/mail.py
amelie/activities/views.py

Whenever a activity was cancelled, the waiting list wasn't informed. Now they will also receive an email.
Fixes/References Inter-Actief/amelie#810
no
no
**Does your PR include CSS changes (and did you run …

Added waiting list activity cancellation mail being sent.

---

amelie/data_export/templates/data_export/dataexport_form.html

Add a note to the data export page that SymposIA data can be retrieved by contacting the board.
Fixed Inter-Actief#356
no
no
The translations should still be processed through Weblate
**Does your PR include CSS changes (and did you run the …

Contact the board for a SymposIA export

---

amelie/personal_tab/static/js/personal_tab_pos.js

Reverts Inter-Actief/amelie#932
Crashes the cookie corner (english version)
```
Uncaught TypeError: article_elem.data(...).replace is not a function
setupShopPage https://www.inter-actief.utwente.nl/static/js/personal_tab_pos.js:493
jQuery 9
setupShopPage https://www.inter-actief.utwente.nl/static/js/personal_tab_pos.js:490
<anonymous> https://www.inter-actief.utwente.nl/personal_tab/pos/shop/:1563
jQuery 13
[personal_tab_pos.js:493:67](https://www.inter-actief.utwente.nl/static/js/personal_tab_pos.js)
```

Revert "Fix dutch cookie corner pricing"

---

amelie/tools/auth.py
amelie/tools/keycloak.py
amelie/views.py
locale/nl/LC_MESSAGES/django.po
templates/profile_overview.html

Implement passkey management on profile page.
Fixes #940
no
no
todo via weblate, strings added …

Add passkey support

---

amelie/education/forms.py
amelie/education/graphql.py
amelie/education/views.py
amelie/settings/generic.py
amelie/test_all_urls.py
amelie/tools/graphql.py
amelie/urls.py
requirements.txt

Add CAPTCHA to public fields (only the educational bouquet) to prevent spamming
Closes #650 
no
yes
yes, I have not included translations yet …

Add CAPTCHA to educational bouquet

---

amelie/settings/generic.py

Fixed amelink being able to switch languages on development
amelie#979
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the …

Added cookie settings for language endpoint for local development

---

amelie/room_duty/templates/room_duty/table/print.html

Takes @SirAppelot (Pepijn)'s request in account: updated the room duty schedule.
Fixes Inter-Actief/amelie#1005
no
no
**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` …

fix: modify room duty schedule
